### ISSUE TITLE
Can't import the named export 'Header' from non EcmaScript module

### ISSUE THREAD

**Issue by vattcarter** [cabify/prom-react#176]
Hi, I am working on a reactjs project written in javascript and I am new to this package.

After I installed the package and used it, the error said
./node_modules/@shopify/react-performance/build/esm/performance-report.mjs
Can't import the named export 'Header' from non EcmaScript module (only default export is available)

"@cabify/prom-react": "0.2.1"

**Comment by alejandrofdiaz** [comment]
Hi! 

I've just checked this is working correctly in most of our applications. I've also checked in a fresh CRA installation.

The export this stack mentioned [belongs](https://github.com/Shopify/quilt/blob/main/packages/react-performance/src/performance-report.ts#L3) to `@shopify/network`, can you double check which version you have installed of this dependency? because in the latest version [it seems to be exported.](https://github.com/Shopify/quilt/blob/main/packages/network/src/network.ts#L59).

This may be also related to how your bundler does resolve dependencies.

**Comment by alejandrofdiaz** [comment]
Can you provide further information on what bundler configuration are you using for your app?

Webpack, rollup, nextjs...

**Comment by 1337-5P34Ker** [comment]
The solution was an update to React 16.14 instead of 16.13.

**Comment by alejandrofdiaz** [comment]
Maybe we should update React peerDependency to `>=16.14`. Thanks for the response, closing this issue.
